# Generated by Django 4.2.3 on 2023-07-12 00:26

import apps.registration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.registration.models.custom_upload_to),
        ),
    ]
